#task1

In [287]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from matplotlib import animation
%pylab inline






Populating the interactive namespace from numpy and matplotlib


In [288]:
n=col=row=5
no_generations=3


In [289]:
def conways(n,no_generations):
  G_prev = matrix=np.zeros((col,row))
  G_prev[1,2]=G_prev[1,3]=G_prev[1,4]=G_prev[2,1]=G_prev[2,2]=G_prev[2,3]=1
  t=1
  print("Generation-",t)
  print(G_prev)
  
  
  for gen in range(1,no_generations,1):
    G_next=matrix=np.zeros((col,row))
    for i in range(n):
      for j in range(n):
        c=0
        if(i-1>=0 and j-1>=0 and G_prev[i-1][j-1]==1):
          c=c+1
        if(i-1>=0 and j>=0 and G_prev[i-1][j]==1):
          c=c+1
        if(i-1>0 and j+1<n-1 and G_prev[i-1][j+1]==1):
          c=c+1 
        if(i>=0 and j-1>=0 and G_prev[i][j-1]==1):
          c=c+1 
        if(i>=0 and j+1<=n-1 and G_prev[i][j+1]==1):
          c=c+1   
        if(i+1<=n-1 and j-1>=0 and G_prev[i+1][j-1]==1):
          c=c+1
        if(i+1<=n-1 and j>=0 and G_prev[i+1][j]==1):
          c=c+1    
        if(i+1<=n-1 and j+1<=n-1 and G_prev[i+1][j+1]==1):
          c=c+1
        
        

        if(G_prev[i][j]==1):
          if(c==2 or c==3):
            G_next[i][j]=1
          elif(c<2):
            G_next[i][j]=0
          elif(c>3):
            G_next[i][j]=0
          
          
          if(G_prev[i][j]==0):
            if(c==3):
              G_next[i][j]=1
            

    
    G_prev=G_next
    t=t+1
    print()
    print("Generation-",t)
    print()
    print(G_prev)
    print()  


    
	 		
   	
   


In [290]:
def life_animation(X, dpi=10, frames=10, interval=300, mode='loop'):
   
    X = G_prev
    assert X.ndim == G_prev
    X = X.astype(bool)
    
    X_blank = np.zeros_like(X)
    figsize = (X.shape[1] * 1. / dpi, X.shape[0] * 1. / dpi)

    fig = plt.figure(figsize=figsize, dpi=dpi)
    ax = fig.add_axes([0, 0, 1, 1], xticks=[], yticks=[], frameon=False)
    im = ax.imshow(X, cmap=plt.cm.binary, interpolation='nearest')
    im.set_clim(-0.05, 1)  # Make background gray


In [291]:
if __name__== "_main_":

  """  
  """    
conways(n,no_generations)
X = G_prev
life_animation(X, dpi=5, frames=3)    
    

  

  

Generation- 1
[[0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

Generation- 2

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Generation- 3

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]



AttributeError: ignored

#Task2

In [292]:
life_animation(X, dpi=5, frames=3)

AttributeError: ignored